version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 714223118758.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(date +%s)
      - echo IMAGE_TAG=$IMAGE_TAG
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t 714223118758.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:$IMAGE_TAG .
      - docker tag 714223118758.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:$IMAGE_TAG 714223118758.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 714223118758.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:$IMAGE_TAG
      - docker push 714223118758.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:latest
      - echo Writing image definition file...
      - printf '[{"name":"my-app-container","imageUri":"714223118758.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:%s"}]' $IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

